### ISSUE TITLE
Comments to paper (JOSS review)

### ISSUE THREAD

**Issue by nluetts** [kellino/DiscreteEntropy.jl#12]
Dear @kellino,

I am opening this in response to the JOSS review https://github.com/openjournals/joss-reviews/issues/7334.

The following is a list of my comments to your paper draft. It is mainly cosmetics, but in two places I think the paper would benefit from some further detail:

**Line 9:**

In the source code, change Equation 1 to:

```
$$H(X) = - \sum_{x \in X} p(x) \log (p(x))$$
```

(remove backslash after `sum`) then LaTeX should render it correctly (you can test it with the Docker image provided by JOSS, https://joss.readthedocs.io/en/latest/paper.html#docker).

**Line 22:**

Reference to Blackwell and Böhme, replace reference in source code to

```
[@bohme:fse:2020;@blackwell2023hyperfuzzing]
```

(delimited by semi-colon), to make the reference parse correctly.

**Line 17:** "Each implementation had a different precision, ..."

Do you mean like 32 vs. 64 bit vs. big float numbers?
If so, why is this a problem?

**Line 23:** Introduce the term "KL divergence".

**Line 39 to 42:** Add references to other packages and tell what
they (do not) cover.

**Line 41:** Remove "those", capitalize "Bub"?

**Line 51:** Change "making it both" to "making them both"

**Code example:**

Delete lines 62 and and 63 and move lines 65 and 66 above the comment
in lines 60 and 61 (62 and 63 are redundant).

**Line 77 to 80:**

Change `title={...}` in source code `paper.bib` to:

```
title = {Nonparametric estimation of {S}hannon's diversity index when there are unseen species in sample.},
```

You can force LaTeX to write "Shannon" with capital S by wrapping
it in curly braces. You can do the same for the reference to Hausser & Strimmer ("James-Stein").

**Line 84 to 87:** Should these references have the same journal information
as Blackwell (arXiv)?

**Line 88:** Delete "Copyright"

**Comment by kellino** [comment]
Hi @nluetts I think I've addressed all the (excellent) comments you suggested. I'll leave this open until you've signed off on the contents.

**Comment by nluetts** [comment]
Hi @kellino 

I think you should cite the other packages in the new paragraph about other estimator implementations differently.
The problem with using just the links to websites is that these external pages may change or get deleted. You should include info about the access date so that readers can try pulling the website from the internet archive, if the link does not work anymore. (Yes, readers could also look at the publication date of your paper, but having the access date right there in the paper makes it easier).
You should also check if the cited packages want a paper to be cited when you reference them. I just checked for the R package `entropy` where it says in the docs (first page, section "Descritption"):

> If you use this package please cite: Jean Hausser and Korbinian Strimmer. 2009. Entropy inference
> and the James-Stein estimator, with application to nonlinear gene association networks. J. Mach.
> Learn. Res. 10: 1469-1484. Available online from https://jmlr.csail.mit.edu/papers/v10/
> hausser09a.html.

Seems like this is the final paper of the arxiv preprint that you cite like so:

```bibtex
@misc{hausser2009entropy,
      title={Entropy inference and the {J}ames-{S}tein estimator, with application to nonlinear gene association networks},
      author={Jean Hausser and Korbinian Strimmer},
      year={2009},
      eprint={0811.3579},
      archivePrefix={arXiv},
      primaryClass={stat.ML}
}
```

so you can change this citation and use it also for `entropy`.

**Comment by kellino** [comment]
Hi @nluetts I'll need a few days to action this as I'm a big snowed under, but I'll get these improvements done over the next few days and ping you when I've finished

**Comment by nluetts** [comment]
Sure, no need to hurry :-)

**Comment by kellino** [comment]
@nluetts any better with the citations? I've included accessed date in the bib information, just in case the links ever die

**Comment by nluetts** [comment]
Yes, this has much improved!

For better looks, you can add spaces before the citations in lines 48, 65-73 and remove the surplus space after `[@chaoshen] , ...` in line 40. (Line numbers refer to markdown source file.)

Otherwise, why not cite the final paper from Hausser and Strimmer instead of the arxiv preprint? The Journal provides the bibtex code:

```
@article{JMLR:v10:hausser09a,
  author  = {Jean Hausser and Korbinian Strimmer},
  title   = {Entropy Inference and the {J}ames-{S}tein Estimator, with Application to Nonlinear Gene Association Networks},
  journal = {Journal of Machine Learning Research},
  year    = {2009},
  volume  = {10},
  number  = {50},
  pages   = {1469-1484},
  url     = {http://jmlr.org/papers/v10/hausser09a.html}
}
```

I also found that JOSS has an example on how to cite GitHub repos (https://joss.readthedocs.io/en/latest/example_paper.html). Accordingly, for `pym` and `ndd` you could do:

```
@misc{pym,
  author = {Pillowlab},
  title = {PYM entropy estimator MATLAB reference implementation},
  year = {2020}, 
  publisher = {GitHub},
  journal = {GitHub repository},
  url = {https://github.com/pillowlab/PYMentropy/},
}

@misc{ndd, 
  author = {Simone Marsili},
  title = {{ndd} - Bayesian entropy estimation from discrete data},
  year = {2021}, 
  publisher = {GitHub},
  journal = {GitHub repository},
  url = {https://github.com/simomarsili/ndd},
} 
``` 

For `nsb` you may want to use the title on sourceforge, ` title = {{NSB} {E}ntropy {E}stimation}`.

Finally, a colon after 

```
These assumptions can have a profound effect on estimations of more complex measures, such as mutual information:
```

in line 101 would make it consistent with line 94.

That should be all with the cosmetics.

**Comment by nluetts** [comment]
So there is one more thing I noticed when reading through the paper a last time just now.

In lines 43 to 44 (in the paper, not source file) you write:

> The PYM(Pillowlab, 2020), BUB(Paninski) and Unseen(Valiant
> & Valiant, 2013) estimators are found ***only in the author’s Matlab implementions***.

I guess the PYM library is yours, but BUB was authored by Paninski and for Unseen a link to the matlab source is not provided (it does not seem to be included in PYM). Can you clarify?

**Comment by kellino** [comment]
Ah, an ambiguous sentence which I'll fix.  "_the  author's_..." does not refer to me (the author of the paper) but the code implementations by the creators of the original estimators. So the PYM estimator exists under the pillowlab user name on github. I'm unaware of any other implementation (except for the one included here). I should have a bit of free time tomorrow to make these last changes to the paper.

**Comment by kellino** [comment]
@nluetts hopefully the ambiguous paragraph should be clearer now. Please let me know. I've also updated the bib file to the github references.

**Comment by nluetts** [comment]
@kellino yes, now the sentence is clear. I ticked off the remaining items in the "Software paper" part of my review list.
