### ISSUE TITLE
Remove Documenter from Dependencies

### ISSUE THREAD

**Issue by nluetts** [kellino/DiscreteEntropy.jl#15]
Hi @kellino 

not something the JOSS review depends upon, but I noticed that DiscreteEntropy installs Documenter when you do 

```julia
] add DiscreteEntropy
```

because of

https://github.com/kellino/DiscreteEntropy.jl/blob/6963a95cf9ba19ad8fc5e8405bef402e07dde25b/Project.toml#L10

and

https://github.com/kellino/DiscreteEntropy.jl/blob/6963a95cf9ba19ad8fc5e8405bef402e07dde25b/Project.toml#L27

But Documenter should only be required for the project that builds the docs, so for the project defined by  `docs/Project.toml/Manifest.toml`. 

I see that you used it also in the tests (doctests?), but then it should be sufficient to add it to the extras/targest section in `Project.toml`:

```
[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
```

Also, your Docs say that Julia 1.11 is currently not supported, but `Project.toml` includes it:

https://github.com/kellino/DiscreteEntropy.jl/blob/6963a95cf9ba19ad8fc5e8405bef402e07dde25b/Project.toml#L36

Nothing terribly important, but for polishing ...

**Comment by kellino** [comment]
Fixed in 8811b18d0324ee310e368df9ad428c1ceedc726d
